---
name: Enhancement Request
description: File an enhancement request
title: "[Enhancement]: "
labels: ["enhancement"]
body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to fill out this enhancement request!
    - type: input
      id: contact
      attributes:
          label: Contact Details
          description: How can we get in touch with you if we need more info?
          placeholder: ex. email@example.com
      validations:
          required: false
    - type: textarea
      id: what-to-enhance
      attributes:
          label: What would you like to enhance?
          description: Also, tell us why this is important.
          placeholder: Tell us what you would like to improve!
          value: "An enhancement request"
      validations:
          required: true
    - type: textarea
      id: logs
      attributes:
          label: Relevant log output
          description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
          render: Shell
    - type: checkboxes
      id: terms
      attributes:
          label: Code of Conduct
          description: By submitting this issue, you agree to follow our [Code of Conduct](.github/CODE_OF_CONDUCT.md)
          options:
              - label: I agree to follow this project's Code of Conduct
                required: true
