---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: lint
on:
    push:
        tags: ["v*.*.*"]
jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                python-version: ["3.10"]
                os: [ubuntu-20.04]
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip setuptools
                  pip install -e .
                  pip install ".[dev]"
            - name: Lint
              run: |
                  make lint-all
