---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: lint
on:
  push:
    tags: ["v*.*.*"]
env:
  pythonVersion: "3.11"
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.11"]
        os: [ubuntu-22.04]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install -e .
          pip install ".[dev]"
      - name: Lint
        run: |
          make lint-all
