---
name: lint
on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint-and-format:
    name: Lint and check formatting for Python code
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Check code formatting
        uses: astral-sh/ruff-action@v3
        with:
          src: ./src
          args: format --check --preview --diff
          version-file: pyproject.toml

      - name: Lint code
        uses: astral-sh/ruff-action@v3
        with:
          src: ./src
          args: check --preview
          version-file: pyproject.toml
