---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: publish a container image to GitHub Packages and Docker Hub
on:
    push:
        tags: ["v*.*.*"]
# env:
jobs:
    push_to_registry:
        name: Push a container image to GitHub Packages and Docker Hub
        runs-on: ubuntu-20.04
        permissions:
            packages: write
            contents: read
        steps:
            - name: Check out the repo
              uses: actions/checkout@v2
            - name: Log in to the GitHub container registry
              if: github.event_name != 'pull_request'
              uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Log in to Docker Hub
              if: github.event_name != 'pull_request'
              uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_TOKEN }}
            - name: Set env RELEASE_VERSION
              run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
            - name: Check env RELEASE_VERSION
              run: |
                  echo ${RELEASE_VERSION}
                  echo ${{ env.RELEASE_VERSION }}
            - name: Check build args
              run: |
                  echo ${GITHUB_SHA}
                  echo ${GITHUB_REF}
                  echo ${RUNNER_ARCH}
                  echo ${RUNNER_OS}
            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
              with:
                  images: |
                      andreygrechin/webcolors
                      ghcr.io/${{ github.repository }}
                  tags: |
                      type=ref,event=branch
                      type=ref,event=pr
                      type=semver,pattern={{version}}
                      type=semver,pattern={{major}}.{{minor}}
            - name: Build and push a container image
              uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
              with:
                  context: .
                  push: ${{ github.event_name != 'pull_request' }}
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  build-args: |
                      GITHUB_SHA=${GITHUB_SHA}
                      GITHUB_REF=${GITHUB_REF}
                      RUNNER_ARCH=${RUNNER_ARCH}
                      RUNNER_OS=${RUNNER_OS}
