---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: publish a container image to GitHub Packages and Docker Hub
on:
    push:
        tags: ["v*.*.*"]
# env:
jobs:
    push_to_registry:
        name: Push a container image to GitHub Packages and Docker Hub
        runs-on: ubuntu-20.04
        permissions:
            packages: write
            contents: read
        steps:
            - name: Check out the repo
              uses: actions/checkout@v2
            - name: Log in to the GitHub container registry
              if: github.event_name != 'pull_request'
              uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Log in to Docker Hub
              if: github.event_name != 'pull_request'
              uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_TOKEN }}
            - name: Set build args
              run: |
                  echo "VERSION_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
                  echo "GITHUB_SHA=${GITHUB_SHA}" >> $GITHUB_ENV
                  echo "GITHUB_REF=${GITHUB_REF}" >> $GITHUB_ENV
                  echo "RUNNER_ARCH=${RUNNER_ARCH}" >> $GITHUB_ENV
                  echo "RUNNER_OS=${RUNNER_OS}" >> $GITHUB_ENV
            - name: Check build args
              run: |
                  echo ${VERSION_TAG}
                  echo ${{ env.VERSION_TAG }}
                  echo ${{ env.GITHUB_SHA }}
                  echo ${{ env.GITHUB_REF }}
                  echo ${{ env.RUNNER_ARCH }}
                  echo ${{ env.RUNNER_OS }}
            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
              with:
                  images: |
                      andreygrechin/webcolors
                      ghcr.io/${{ github.repository }}
                  tags: |
                      type=ref,event=branch
                      type=ref,event=pr
                      type=semver,pattern={{version}}
                      type=semver,pattern={{major}}.{{minor}}
            - name: Build and push a container image
              uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
              with:
                  context: .
                  push: ${{ github.event_name != 'pull_request' }}
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  build-args: |
                      VERSION_TAG=${{ env.VERSION_TAG }}
                      GITHUB_SHA=${{ env.GITHUB_SHA }}
                      GITHUB_REF=${{ env.GITHUB_REF }}
                      RUNNER_ARCH=${{ env.RUNNER_ARCH }}
                      RUNNER_OS=${{ env.RUNNER_OS }}
